implement http and https choice in configure file

diff --git a/raspberry/configure b/raspberry/configure
--- a/raspberry/configure
+++ b/raspberry/configure
@@ -1,13 +1,26 @@
 #!/bin/bash
 
+echo "Do you want to use HTTP or HTTPS connection? Type 1 for HTTP and 2 for HTTPS:"
+read connection_type
+
+if [ "$connection_type" = "1" ]; then
+    connection_type="http"
+elif [ "$connection_type" = "2" ]; then
+    connection_type="https"
+else
+    echo "Invalid input. Please enter either 1 for HTTP or 2 for HTTPS."
+    exit 1
+fi
+
 echo "Enter web_server_address: "
 read web_server_address
 
-# Check if web_server_address is a valid IP address
-# if ! [[ "$web_server_address" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
-#     echo "Error: web_server_address must be a valid IP address."
-#     exit 1
-# fi
+# Add "http://" or "https://" to the web server address
+if [ "$connection_type" = "http" ]; then
+    web_server_address="http://$web_server_address"
+elif [ "$connection_type" = "https"]; then
+    web_server_address="https://$web_server_address"
+fi
 
 echo "Enter default_transmission_interval in seconds: "
 read default_transmission_interval
@@ -18,7 +31,7 @@ if ! [[ "$default_transmission_interval" =~ ^[0-9]+$ ]]; then
     exit 1
 fi
 
-# CHeck if access_point_name is empty
+# Check if access_point_name is empty
 echo "Enter access_point_name: "
 read access_point_name
 
