add additional safety features to configure script

diff --git a/raspberry/configure b/raspberry/configure
--- a/raspberry/configure
+++ b/raspberry/configure
@@ -1,12 +1,16 @@
 #!/bin/bash
 
-# Create conf.yaml file
 echo "Enter web_server_address: "
 read web_server_address
+
+# Check if web_server_address is a valid IP address
+if ! [[ "$web_server_address" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
+    echo "Error: web_server_address must be a valid IP address."
+    exit 1
+fi
+
 echo "Enter initial_transfer_interval in seconds: "
 read initial_transfer_interval
-echo "Enter access_point_name: "
-read access_point_name
 
 # Check if initial_transfer_interval is an integer
 if ! [[ "$initial_transfer_interval" =~ ^[0-9]+$ ]]; then
@@ -14,10 +18,13 @@ if ! [[ "$initial_transfer_interval" =~ ^[0-9]+$ ]]; then
     exit 1
 fi
 
-# Check if web_server_address is a valid IP address
-if ! [[ "$web_server_address" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-    echo "Error: web_server_address must be a valid IP address."
-    exit 1
+# CHeck if access_point_name is empty
+echo "Enter access_point_name: "
+read access_point_name
+
+if [ -z "$access_point_name" ]; then
+  echo "Access point name cannot be empty."
+  exit 1
 fi
 
 # Write configuration to conf.yaml
